// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCC0rOC930AMQ2isEjiXPHEFqz-WmQ7plc',
    appId: '1:228314848211:web:31e414226672767a00ed26',
    messagingSenderId: '228314848211',
    projectId: 'track-all-prg',
    authDomain: 'track-all-prg.firebaseapp.com',
    storageBucket: 'track-all-prg.firebasestorage.app',
    measurementId: 'G-PBQRJ0CCV2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOKYjunRYTiasvxsktut2iVJTpVWqfzN4',
    appId: '1:228314848211:android:138c5eb8d14a8aac00ed26',
    messagingSenderId: '228314848211',
    projectId: 'track-all-prg',
    storageBucket: 'track-all-prg.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-bfctVJedcnekksK7JpzIrtJ3Ix5-shU',
    appId: '1:228314848211:ios:6ec16ad8c5d444c700ed26',
    messagingSenderId: '228314848211',
    projectId: 'track-all-prg',
    storageBucket: 'track-all-prg.firebasestorage.app',
    iosBundleId: 'com.prangroup.mis93.tmbi',
  );

}