// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3NA4y7Tyegu62vDkMotdiCvlsFx-qDxA',
    appId: '1:293076147542:web:511f603b97c98137128af7',
    messagingSenderId: '293076147542',
    projectId: 'track-all-42507',
    authDomain: 'track-all-42507.firebaseapp.com',
    storageBucket: 'track-all-42507.firebasestorage.app',
    measurementId: 'G-DCW7EH6QYS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSo8hPerqHqSqA1ySCgZv5pmLJY-zUwkg',
    appId: '1:293076147542:android:7fc7520b9e1642a7128af7',
    messagingSenderId: '293076147542',
    projectId: 'track-all-42507',
    storageBucket: 'track-all-42507.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpLqBqKKRiXC_1sOdjJfxDJmIVD80fzQM',
    appId: '1:293076147542:ios:acc691c85d994ec6128af7',
    messagingSenderId: '293076147542',
    projectId: 'track-all-42507',
    storageBucket: 'track-all-42507.firebasestorage.app',
    iosBundleId: 'com.prangroup.mis93.tmbi',
  );
}
